Translate comment in English
WildCodeSchool/quest-java-oop1 pull request #1
Opened 2019-10-29 22:25 UTC by florianpdf

English translation of comment

2019-10-30 07:44 UTC, bastienapp requested changes

2019-10-30 07:44 UTC, bastienwcs commented on Pond.java
> +        // the riri reference receives a new instance of the Duck class
riri's reference receives a new instance of the Duck class

2019-10-30 07:44 UTC, bastienwcs commented on Pond.java
> +        // use of getters
getters usage

2019-10-30 07:44 UTC, bastienwcs commented on Pond.java
> +        // use of setter
setter usage

2019-10-30 07:44 UTC, bastienwcs commented on Pond.java
> +        // both point to the same memory space:
both aim to the same memory space

2019-11-25 07:41 UTC, bhubr commented
Fixed by #3

2019-11-25 07:41 UTC, closed without merging