Translation
WildCodeSchool/quest-java-oop1 pull request #2
Opened 2019-10-29 22:26 UTC by florianpdf

Translation of comments

2019-10-30 07:40 UTC, bastienapp requested changes

2019-10-30 07:40 UTC, bastienwcs commented on Duck.java
> +    // mutators (setters)
setters

2019-10-30 07:40 UTC, bastienwcs commented on Duck.java
> +    // accessors (getters)
getters

2019-11-25 07:41 UTC, bhubr commented
Fixed by #3

2019-11-25 07:41 UTC, closed without merging